import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "../components/navbar/navbar";
import "./globals.css";
import { SocketProvider } from "@/context/socketContext";
import { Web3AuthProvider } from "@/context/web3AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Web3AuthProvider>
          <SocketProvider>
            <Navbar />
            {children}
          </SocketProvider>
        </Web3AuthProvider>
      </body>
    </html>
  );
}
